#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-photos
Version  : 43.0
Release  : 32
URL      : https://download.gnome.org/sources/gnome-photos/43/gnome-photos-43.0.tar.xz
Source0  : https://download.gnome.org/sources/gnome-photos/43/gnome-photos-43.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: tracker-miners-data
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : desktop-file-utils
BuildRequires : gdk-pixbuf
BuildRequires : gegl-dev
BuildRequires : gexiv2-dev
BuildRequires : itstool
BuildRequires : libjpeg-turbo-dev
BuildRequires : pkgconfig(geocode-glib-1.0)
BuildRequires : pkgconfig(geocode-glib-2.0)
BuildRequires : pkgconfig(goa-1.0)
BuildRequires : pkgconfig(grilo-0.3)
BuildRequires : pkgconfig(libdazzle-1.0)
BuildRequires : pkgconfig(libgdata)
BuildRequires : pkgconfig(libgfbgraph-0.2)
BuildRequires : pkgconfig(libhandy-1)
BuildRequires : pkgconfig(tracker-sparql-3.0)
BuildRequires : pygobject-python
BuildRequires : yelp-tools-dev

%description
Photos - access, organize and share your photos on GNOME
========================================================

%prep
%setup -q -n gnome-photos-43.0
cd %{_builddir}/gnome-photos-43.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1663965804
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gnome-photos
cp %{_builddir}/gnome-photos-%{version}/COPYING %{buildroot}/usr/share/package-licenses/gnome-photos/31a3d460bb3c7d98845187c716a30db81c44b615 || :
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)
